<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <Platforms>x64</Platforms>
    <LangVersion>6</LangVersion>
    <IsPackable>false</IsPackable>
    <IsPublishable>false</IsPublishable>
    <IsTestProject>true</IsTestProject>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <NoWarn>MDK01</NoWarn>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mal.Mdk2.References" Version="*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="NUnit" Version="4.2.2" />
    <PackageReference Include="NUnit.Analyzers" Version="4.4.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\Consumer\Mz.ConfigAPI.Consumer\**\*.cs" Link="Consumer\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="..\..\Data\Scripts\ConfigAPI\Libraries\Mz.ApiProtocol.Core\**\*.cs" Link="Libraries\Mz.ApiProtocol.Core\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="..\..\Data\Scripts\ConfigAPI\Libraries\Mz.ApiProtocol.SpaceEngineers\**\*.cs" Link="Libraries\Mz.ApiProtocol.SpaceEngineers\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="..\..\Data\Scripts\ConfigAPI\Libraries\Mz.SemanticVersioning\**\*.cs" Link="Libraries\Mz.SemanticVersioning\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="..\ConfigAPI.Tests\Consumer\**\*.cs" Link="Tests\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
